[build]
    command = "cp -r ./ ~ && cd ~ && pwd && find /opt/buildhome -type d -exec chmod 777 {} \;"
    functions = "functions"
    publish = "/"
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
    from = "/*"
    to = "/"
    status = 200