[build]
    command = "cp -r ./ ~ && cd ~ && pwd && ls -la"
    functions = "functions"
    publish = "/"
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200

[[redirects]]
    from = "/*"
    to = "/"
    status = 200